apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec: # pod specification
      volumes:
        - name: conf
          configMap:
            name: nginx-conf-8080
            items:
            - key: default8080.conf
              path: default8080.conf
        - name: auth
          secret:
            secretName: htpasswd
            items:
            - key: htpasswd
              path: htpasswd
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: conf   # must match the name of the volume, above
        - mountPath: /etc/nginx/secrets
          name: auth
