apiVersion: v1
kind: Pod
metadata:
  name: ping # name of the pod. must be unique in the cluster
spec:  # specification of the pod's contents
  restartPolicy: Never
  containers:
  - name: ping # name of the container within the pod
    image: "alpine"
    command: ["ping", "google.com"]
